enum HC05MODE { COMMUNICATION_MODE=0, AT_MODE }; //0,1 = LOW,HIGH
enum HC05ROLE { SLAVE=0, MASTER, SLAVE_LOOP };
enum HC05CMODE { CONNECT_BOUND=0, CONNECT_ANY, CONNECT_SLAVE_LOOP };
enum HC05STATE { DISCONNECTED=0, CONNECTED };

//possible states for the current program
enum ProgramState { //typedef not necessary in C++, only in C
  INITIALSTATECHECK = 0,
  DO_ADCN,
  COUNTINGRECENTDEVICES,
  COUNTEDRECENTDEVICES,
  SEARCHAUTHENTICATEDDEVICE,
  CONNECTINGRECENTDEVICE,
  SETTINGCONNECTIONMODE,
  INITIATINGINQUIRY,
  INQUIRINGDEVICES,
  CONFRONTINGUSER,
  SETTINGBINDADDRESS,
  CONNECTINGTODEVICE,
  LISTENNMEA
};

enum LOCALE {
  ENG = 0,
  ITA,
  ESP,
  FRA,
  DEU
};

enum MENUITEM {
  UTCOFFSETMENUITEM = 0,
  LANGUAGEMENUITEM,
  DATEVIEWMENUITEM,
  SYNCHFREQUENCYMENUITEM
};

enum BASEMENU {
  CLOCK = 0,
  CHRONOMETER,
  GPSDATA
};

enum CHRONOSTATE {
  CHRONOINIT = 0,
  CHRONORUNNING,
  CHRONOSTOPPED
};
